name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout glass
        uses: actions/checkout@v4
        with:
          repository: obscurelyme/glass
          token: ${{secrets.GLASS_GH_PAT}}
          path: .github/actions/glass

      - name: Run Glass CLI
        uses: ./github/actions/glass
        with:
          command: validate --infra infrastructure/template.yaml
