name: Deploy Function

on:
  push:
    branches:
      - main
    tags:
      - "v*"

env:
  AWS_REGION: us-east-1
  GLASS_VERSION: v0.0.15
  FUNCTION_NAME: ${{ github.event.repository.name }}
  BINARY_ZIP: bootstrap.zip
  GOPRIVATE: github.com/obscurelyme/*

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Log into AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com
          mask-aws-account-id: "true"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git for private modules
        run: git config --global url."https://${{ secrets.GLASS_GH_PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Test
        run: >
          make test

      - name: Package
        run: >
          make package

      - name: Checkout glass
        uses: actions/checkout@v4
        with:
          repository: obscurelyme/glass
          token: ${{secrets.GLASS_GH_PAT}}
          path: .github/actions/glass
          ref: ${{ env.GLASS_VERSION }}

      - name: Run Glass CLI
        uses: ./.github/actions/glass
        with:
          token: ${{secrets.GLASS_GH_PAT}}
          command: lambda upload --function ${{ env.FUNCTION_NAME }} --binary ${{ env.BINARY_ZIP }}
