name: Glass | Deployment Workflow

on:
  workflow_call:
    inputs:
      stack_action:
        description: "Deployment action to take on the stack"
        required: true
        type: string
      glass_version:
        type: string
        default: latest
      aws_region:
        type: string
        default: us-east-1

jobs:
  glass-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Log into AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_IAM_ROLE }}
          aws-region: ${{ inputs.aws_region }}
          audience: sts.amazonaws.com
          mask-aws-account-id: "true"

      - name: Checkout glass
        uses: actions/checkout@v4
        with:
          repository: obscurelyme/glass
          token: ${{secrets.GLASS_GH_PAT}}
          path: .github/actions/glass
          ref: ${{ inputs.glass_version }}

      - name: Run Glass CLI
        uses: ./.github/actions/glass
        with:
          token: ${{secrets.GLASS_GH_PAT}}
          command: cfn ${{inputs.stack_action}} --infra ./infrastructure --admin
